#!/usr/bin/env bash
# A script that installs nginx server
# And serves a default page index.html on the HTTP  GET request

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' | sudo tee /var/www/html/index.html

sudo nginx -t

service nginx restart
