#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if

num=1

while [ $num -le 10 ]
do
    echo "Best School"
    if [ $num -eq 9 ]
    then
        echo "Hi"
    fi
    ((num++))
done
