#!/usr/bin/env bash
# A script that prints bad luck, good luck and Best school

num=1

while [ $num -le 10 ]
do
    if [ $num -eq 4 ]
    then
        echo "bad luck"
    elif [ $num -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((num++))
done
